name: Update Spotify Track in README

on:
  schedule:
    - cron: '0 * * * *'  # Esto se ejecutará cada hora, puedes ajustar el cron según lo desees
  workflow_dispatch:  # Permite ejecutar manualmente la acción desde GitHub

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install spotipy jq

    - name: Run Python script to get track data
      run: |
        python ./scripts/get_spotify_track.py  # Ejecutamos el script desde la carpeta 'scripts'

    - name: Read track data from JSON and update README
      run: |
        # Leer los datos del archivo JSON generado por el script
        TRACK_NAME=$(jq -r '.track_name' track_data.json)
        TRACK_URL=$(jq -r '.track_url' track_data.json)
        TRACK_IMAGE=$(jq -r '.track_image' track_data.json)

        # Reemplazar las URLs en el README
        sed -i "s|https://i.scdn.co/image/.*|$TRACK_IMAGE|g" README.md
        sed -i "s|https://open.spotify.com/track/.*|$TRACK_URL|g" README.md

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update Spotify track in README"
        git push
